
import React, { useState, useEffect } from 'react';
import { getSustainabilityInsights } from '../services/gemini';

const AiInsights: React.FC = () => {
  const [insight, setInsight] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const totalBottles = 12482; // Simulated total

  const fetchInsights = async () => {
    setLoading(true);
    const result = await getSustainabilityInsights(totalBottles);
    setInsight(result);
    setLoading(false);
  };

  useEffect(() => {
    fetchInsights();
  }, []);

  return (
    <div className="space-y-6">
      <div className="bg-gradient-to-br from-green-600 to-emerald-700 rounded-3xl p-8 text-white shadow-xl">
        <div className="max-w-3xl">
          <div className="flex items-center space-x-3 mb-4">
            <i className="fas fa-brain text-2xl opacity-80"></i>
            <h2 className="text-2xl font-bold">AI Impact Analysis</h2>
          </div>
          <p className="text-green-50 text-lg leading-relaxed">
            Our Gemini-powered analysis calculates the real-world environmental savings generated by the GreenPoints community.
          </p>
          <div className="mt-8 grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="bg-white/10 backdrop-blur-md rounded-2xl p-4 border border-white/20">
              <span className="block text-green-200 text-xs font-bold uppercase mb-1">Total Bottles</span>
              <span className="text-2xl font-bold">{totalBottles.toLocaleString()}</span>
            </div>
            <div className="bg-white/10 backdrop-blur-md rounded-2xl p-4 border border-white/20">
              <span className="block text-green-200 text-xs font-bold uppercase mb-1">Recycling Rate</span>
              <span className="text-2xl font-bold">84%</span>
            </div>
            <div className="bg-white/10 backdrop-blur-md rounded-2xl p-4 border border-white/20">
              <span className="block text-green-200 text-xs font-bold uppercase mb-1">Status</span>
              <span className="text-2xl font-bold">Optimal</span>
            </div>
          </div>
        </div>
      </div>

      <div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-8">
        <div className="flex justify-between items-center mb-6">
          <h3 className="text-xl font-bold text-slate-800">Environmental Savings Report</h3>
          <button 
            onClick={fetchInsights}
            disabled={loading}
            className="flex items-center space-x-2 text-green-600 font-bold hover:text-green-700 disabled:opacity-50"
          >
            <i className={`fas fa-sync-alt ${loading ? 'animate-spin' : ''}`}></i>
            <span>Refresh Analysis</span>
          </button>
        </div>

        {loading ? (
          <div className="flex flex-col items-center justify-center py-12 space-y-4">
            <div className="w-12 h-12 border-4 border-green-100 border-t-green-600 rounded-full animate-spin"></div>
            <p className="text-slate-400 font-medium">Gemini is analyzing ecological data...</p>
          </div>
        ) : (
          <div className="prose max-w-none text-slate-600 whitespace-pre-line bg-slate-50 p-6 rounded-2xl border border-slate-100">
            {insight || "No data available."}
          </div>
        )}

        <div className="mt-8 grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="p-6 bg-slate-900 rounded-2xl text-white">
            <h4 className="font-bold mb-2">Predictive Maintenance</h4>
            <p className="text-slate-400 text-sm">AI predicts Bin-03 will be full by 4:00 PM today based on historical Friday patterns. Staff notified.</p>
          </div>
          <div className="p-6 bg-blue-600 rounded-2xl text-white">
            <h4 className="font-bold mb-2">Peak Hours Optimization</h4>
            <p className="text-blue-100 text-sm">The cafeteria bin receives 60% of daily volume between 12-1 PM. Suggested action: Add secondary bin.</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AiInsights;
